[build]
  publish = "dist"    
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"   
  VITE_BOLT_DATABASE_URL = "$VITE_BOLT_DATABASE_URL"
  VITE_BOLT_DATABASE_ANON_KEY = "$VITE_BOLT_DATABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
